name: home_monitor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iot_client_starter:
    git:
      url: https://github.com/NikitaMasev/iot_client_starter.git
      ref: main

  #UI
  flutter_native_splash: ^2.3.2
  theme_provider: ^0.6.0
  circular_bottom_navigation: ^2.3.0
  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.7

  #Navigation
  auto_route: ^7.8.3

  #Architecture
  flutter_bloc: ^8.1.3

  #DI
  provider: ^6.0.5

  #Utils
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.1
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_gen:
  output: lib/presentation/assets_paths
  integrations:
    flutter_svg: true

#flutter_icons:
#  image_path: "assets/png/launcher.png"
#  android: true
