name: home_monitor
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iot_client_starter:
    git:
      url: https://github.com/NikitaMasev/iot_client_starter.git
      ref: main
  dfa_common:
    git:
      url: https://github.com/NikitaMasev/dfa_common.git
      ref: main
  crypto_wrapper:
    git:
      url: https://github.com/NikitaMasev/crypto_wrapper.git
      ref: main

  #UI
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  flex_color_picker: ^3.3.0
  sleek_circular_slider: ^2.0.1
  widget_slider: ^0.1.0

  #Navigation
  auto_route: ^7.8.3

  #Architecture
  flutter_bloc: ^8.1.3

  #DI
  provider: ^6.0.5

  #Network
  dio: ^5.3.3

  #Utils
  device_info_plus: ^9.1.0
  r_upgrade: ^0.4.2
  permission_handler: ^11.0.1
  package_info_plus: ^4.2.0
  freezed: ^2.4.5

  #DB
  shared_preferences: ^2.2.1

  #Analytics
  sentry_flutter: ^7.10.1

dev_dependencies:
  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.1
  icons_launcher: ^2.1.3
  freezed_annotation: ^2.4.1
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

flutter_gen:
  output: lib/presentation/assets_paths
  integrations:
    flutter_svg: true

icons_launcher:
  image_path: "assets/png/launcher_home.png"
  platforms:
    android:
      enable: true
